### PR TITLE
Connectomes

### PR DESCRIPTION
**Pull request by russelljjarvis**
Another draft PR.

This code shows how Plugin matrix capabilities almost work.

### CODE REVIEW

**Comment by bjarthur** [comment]
the only code that needs to be in this PR is that in src/contrib/genPotjansConnectivity.jl.  and that should be split into two files, one with the definition of genStaticWeights and the other with genPlasticWeights.  the rest is just your test harness and shouldn't be committed.

**Comment by russelljjarvis** [comment]
AOK, that makes sense, I will revise and update.

**Comment by russelljjarvis** [comment]
I still remember this PR. I am currently pre-occupied with lab work, but I am also incentivized by my lab to make this PR suitable.

**Comment by russelljjarvis** [comment]
Okay. I have done rebasing and boiled this down to six commits.

I have also synced back up with your branch.

**Comment by russelljjarvis** [comment]
Abandoned in favor of new less commits alternative.
https://github.com/SpikingNetwork/TrainSpikingNet.jl/pull/7

**Pull request closed without merging**
